### ISSUE TITLE
ABH Export is too verbose

### ISSUE THREAD

**Issue by laceysanderson** [UofS-Pulse-Binfo/vcf_filter#15]
When exporting a VCF as ABH format, the module prints to the screen for each site skipped. This can be extremely verbose in large VCFs.

> Skipping site: ( LcContig97429 23317 ) due to missing call in ILL_1704
> Skipping site: ( LcContig97429 23336 ) due to missing call in ILL_1704
> Skipping site: ( LcContig97429 23343 ) due to missing call in ILL_1704
> Skipping site: ( LcContig97429 23378 ) due to missing call in ILL_1704
> Skipping site: ( LcContig97429 23380 ) due to missing call in ILL_1704
> Skipping site: ( LcContig97429 23393 ) due to missing call in ILL_1704
> Skipping site: ( LcContig97429 23924 ) due to missing call in ILL_1704
> Skipping site: ( LcContig97429 23971 ) due to missing call in ILL_1704
> Skipping site: ( LcContig97429 43770 ) due to missing call in Robin
> Skipping site: ( LcContig97483 54893 ) due to missing call in Robin
> Skipping site: ( LcContig97594 459 ) due to a heterozygous call in Robin
> Skipping site: ( LcContig97594 464 ) due to a heterozygous call in Robin
> Skipping site: ( LcContig97594 589 ) due to parents having matching genotype: 0/0
> Skipping site: ( LcContig97594 757 ) due to a heterozygous call in ILL_1704
> Skipping site: ( LcContig97659 107021 ) due to a heterozygous call in Robin
> Skipping site: ( LcContig97659 108627 ) due to missing call in ILL_1704
> Skipping site: ( LcContig97659 109159 ) due to a heterozygous call in ILL_1704
> Skipping site: ( LcContig97659 158671 ) due to a heterozygous call in Robin
> Skipping site: ( LcContig97659 158683 ) due to a heterozygous call in Robin
> Skipping site: ( LcContig97659 159673 ) due to a heterozygous call in Robin
> Skipping site: ( LcContig97659 160269 ) due to a heterozygous call in Robin
> Skipping site: ( LcContig97659 160270 ) due to a heterozygous call in Robin
> Skipping site: ( LcContig97659 160394 ) due to a heterozygous call in Robin
> Skipping site: ( LcContig97659 183118 ) due to missing call in ILL_1704
> Skipping site: ( LcContig97659 183151 ) due to missing call in ILL_1704
> Skipping site: ( LcContig97659 183991 ) due to missing call in ILL_1704
> Skipping site: ( LcContig97659 185227 ) due to missing call in ILL_1704
> Skipping site: ( LcContig97659 185278 ) due to missing call in ILL_1704
> Skipping site: ( LcContig97856 49252 ) due to missing call in Robin
> Skipping site: ( LcContig97856 49275 ) due to missing call in Robin
> Skipping site: ( LcContig97856 49276 ) due to missing call in Robin
> Skipping site: ( LcContig97856 49605 ) due to missing call in ILL_1704
> Skipping site: ( LcContig97856 49606 ) due to missing call in ILL_1704
> Skipping site: ( LcContig97856 49708 ) due to missing call in ILL_1704
> Skipping site: ( LcContig97865 44556 ) due to missing call in ILL_1704
> Skipping site: ( LcContig97865 44645 ) due to missing call in ILL_1704
> Skipping site: ( LcContig97865 44922 ) due to missing call in ILL_1704
> Skipping site: ( LcContig97865 44934 ) due to missing call in ILL_1704
> Skipping site: ( LcContig97865 47397 ) due to missing call in ILL_1704
> Skipping site: ( LcContig97865 47407 ) due to missing call in ILL_1704
> Skipping site: ( LcContig97865 47450 ) due to missing call in ILL_1704
> Skipping site: ( LcContig97865 47521 ) due to missing call in ILL_1704
> Skipping site: ( LcContig97929 22592 ) due to a heterozygous call in ILL_1704
> Skipping site: ( LcContig97929 22945 ) due to a heterozygous call in ILL_1704
> Skipping site: ( LcContig98036 23019 ) due to missing call in Robin
> Skipping site: ( LcContig98036 23074 ) due to missing call in Robin
> Skipping site: ( LcContig98036 82486 ) due to missing call in Robin
> Skipping site: ( LcContig98036 82487 ) due to missing call in Robin
> Skipping site: ( LcContig98036 82492 ) due to parents having matching genotype: 0/0
> Skipping site: ( LcContig98036 82493 ) due to parents having matching genotype: 0/0
> Skipping site: ( LcContig98036 82948 ) due to missing call in ILL_1704
> Skipping site: ( LcContig98036 88534 ) due to missing call in Robin
> Skipping site: ( LcContig98036 88625 ) due to missing call in Robin
> Skipping site: ( LcContig98036 89454 ) due to missing call in Robin
> Skipping site: ( LcContig98036 89474 ) due to missing call in Robin
> Skipping site: ( LcContig98036 89484 ) due to missing call in Robin
> Skipping site: ( LcContig98081 6106 ) due to parents having matching genotype: 0/0
> Skipping site: ( LcContig98317 34799 ) due to missing call in ILL_1704
> Skipping site: ( LcContig98317 50674 ) due to missing call in ILL_1704
> Skipping site: ( LcContig98317 50679 ) due to missing call in ILL_1704
> Skipping site: ( LcContig98317 50682 ) due to missing call in ILL_1704
> Skipping site: ( LcContig98317 50683 ) due to missing call in ILL_1704
> Skipping site: ( LcContig98317 50692 ) due to parents having matching genotype: 0/0
> Skipping site: ( LcContig98317 50695 ) due to parents having matching genotype: 1/1
> Skipping site: ( LcContig98317 50699 ) due to parents having matching genotype: 1/1
> Skipping site: ( LcContig98317 50737 ) due to parents having matching genotype: 0/0
> Skipping site: ( LcContig98317 51794 ) due to missing call in Robin
> Skipping site: ( LcContig98317 57801 ) due to missing call in ILL_1704
> Skipping site: ( LcContig984 8032 ) due to a heterozygous call in Robin
> Skipping site: ( LcContig984 9325 ) due to missing call in ILL_1704
> Skipping site: ( LcContig984 9326 ) due to missing call in ILL_1704
> Skipping site: ( LcContig98698 44821 ) due to missing call in Robin
> Skipping site: ( LcContig98698 45865 ) due to missing call in Robin
> Skipping site: ( LcContig98698 45901 ) due to missing call in Robin
> Skipping site: ( LcContig98698 46907 ) due to missing call in ILL_1704
> Skipping site: ( LcContig98698 51129 ) due to missing call in ILL_1704
> Skipping site: ( LcContig9874 11226 ) due to a heterozygous call in Robin
> Skipping site: ( LcContig9874 11229 ) due to a heterozygous call in Robin
> Skipping site: ( LcContig98861 13459 ) due to missing call in Robin
> Skipping site: ( LcContig99030 4798 ) due to a heterozygous call in ILL_1704
> Skipping site: ( LcContig99030 4799 ) due to a heterozygous call in ILL_1704
> Skipping site: ( LcContig99030 5837 ) due to a heterozygous call in Robin
> Skipping site: ( LcContig99103 11090 ) due to a heterozygous call in Robin
> Skipping site: ( LcContig99103 11104 ) due to a heterozygous call in Robin
> Skipping site: ( LcContig99103 11206 ) due to a heterozygous call in Robin
> Skipping site: ( LcContig99103 11219 ) due to a heterozygous call in Robin
> Skipping site: ( LcContig99103 11237 ) due to a heterozygous call in ILL_1704
> Skipping site: ( LcContig99177 16559 ) due to missing call in ILL_1704
> Skipping site: ( LcContig99178 543 ) due to missing call in ILL_1704
> Skipping site: ( LcContig99178 22227 ) due to missing call in Robin
> Skipping site: ( LcContig99178 23450 ) due to missing call in Robin
> Skipping site: ( LcContig99178 23604 ) due to missing call in Robin
> Skipping site: ( LcContig99178 23625 ) due to missing call in Robin
> Skipping site: ( LcContig99178 32490 ) due to missing call in Robin
> Skipping site: ( LcContig99178 32630 ) due to missing call in Robin
> Skipping site: ( LcContig99178 85016 ) due to missing call in Robin
> Skipping site: ( LcContig99178 131605 ) due to missing call in ILL_1704
> Skipping site: ( LcContig99178 151037 ) due to missing call in Robin
> Skipping site: ( LcContig9926 18061 ) due to missing call in ILL_1704
> Skipping site: ( LcContig99537 3725 ) due to missing call in ILL_1704
> Skipping site: ( LcContig99537 3735 ) due to missing call in ILL_1704
> Skipping site: ( LcContig99556 11322 ) due to a heterozygous call in ILL_1704
> Skipping site: ( LcContig99556 12169 ) due to a heterozygous call in ILL_1704
> Skipping site: ( LcContig99556 12255 ) due to a heterozygous call in ILL_1704
> Skipping site: ( LcContig99556 21684 ) due to missing call in Robin
> Skipping site: ( LcContig99556 22417 ) due to missing call in ILL_1704
> Skipping site: ( LcContig99770 3285 ) due to missing call in ILL_1704
> Skipping site: ( LcContig99770 3288 ) due to missing call in ILL_1704

**Comment by Jiu9Shen** [comment]
Hide a total of 6 screen prints:
'print "Skipping site: ( $chrom $pos ) due to multiple alternate alleles: $alt_alleles\n";'
'print "Skipping site: ( $chrom $pos ) due to missing call in $maternal_parent\n";'
'print "Skipping site: ( $chrom $pos ) due to a heterozygous call in $maternal_parent\n";'
'print "Skipping site: ( $chrom $pos ) due to missing call in $paternal_parent\n";'
'print "Skipping site: ( $chrom $pos ) due to a heterozygous call in $paternal_parent\n";'
'print "Skipping site: ( $chrom $pos ) due to parents having matching genotype: $genotype_calls[0]/$genotype_calls[1]\n";'

**Comment by laceysanderson** [comment]
Done
