### ISSUE TITLE
Description update for Miner Allele Frequency and Maximun Missing Frequency

### ISSUE THREAD

**Issue by Jiu9Shen** [UofS-Pulse-Binfo/vcf_filter#16]
Problem for current filtering descriptions of Miner Allele Frequency (MAF) and Maximun Missing Frequency (MMF) is they are neither not very accurate or not match our code.
Suggestion for MAF:
Update description about 50% because users input should between in range of [0 50], 50% is not a good example.

Suggestion for MMF:
Current description is wrong, don't change description but change code.

**Comment by Jiu9Shen** [comment]
About MMF, I was wrong, current description matches code. The logic is (20% as example):

**Comment by laceysanderson** [comment]
Fixed by PR
