### ISSUE TITLE
Create ReadtheDocs

### ISSUE THREAD

**Issue by Jiu9Shen** [UofS-Pulse-Binfo/vcf_filter#28]
We need ReadtheDocs for first release.

**Comment by Jiu9Shen** [comment]
List of steps:
**Features**
**Dependencies**
**Installation**
1. Download vcf_filter to specific directory from Github
2. Check/install dependencies
3. Enable module "VCF Filter"
**Usage**
4. Load file: fill in correspond info of the file 
5. Give permission to group/individual
6. Test 
**Screenshots**

**Comment by laceysanderson** [comment]
Looks good. I would add the screenshots to the features rather then have both sections. Also I would move dependencies into the installation :-)

**Comment by laceysanderson** [comment]
PR Merged
