### ISSUE TITLE
Allow the user to download a SNP matrix format

### ISSUE THREAD

**Issue by carolyncaron** [UofS-Pulse-Binfo/vcf_filter#4]
We want to provide a straightforward SNP matrix (SNP positions as rows, individuals as columns) as a downloadable option by this module.

**Comment by carolyncaron** [comment]
Somebody in our group has requested help with converting a VCF file into Hapmap format. Seeing as this format is very close to a generic SNP matrix, only with more detail, perhaps I should focus on implementing the ability to download Hapmap instead.

**Comment by laceysanderson** [comment]
Fixed via PR
